microsoft/VSProjectSystem

- doc/overview/Contentitem_types.md
- doc/overview/CookBook.md
- doc/overview/Define_a_new_project_type.md
- doc/overview/Interfaces_NOT_defined_on_IVsProject_object.md
- doc/overview/Interfaces_defined_on_IVsProject_object.md
- doc/overview/ItemIDs.md
- doc/overview/MEF.md
- doc/overview/Project_configurations.md
- doc/overview/Responsive_design.md
- doc/overview/about_project_capabilities.md
- doc/overview/index.md
- doc/overview/intro.md
- doc/overview/obligations.md
Not much actual content changes at all. Mostly just adding LFs where they were missing, backticks, and a few minor typo corrections.
> Next set of files cleaned up

- doc/Index.md
- doc/overview/reference_implementations.md
> Add NuProj link as a reference implementation

- doc/scenario/analyze_hangs.md
This migrates more material we have internally to the public docs.
> Async hang debugging

- doc/extensibility/project_item_templates.md
- doc/scenario/provide_custom_icons_for_the_project_or_item_type.md
Updating the documentation per thread #46.
> Documentation on how to add custom icons

- doc/Index.md
- doc/extensibility/IDynamicEnumValuesProvider.md
- doc/extensibility/project_item_templates.md
> Document dynamic enum values provider

- doc/overview/project_capabilities.md
> Add JavaScript and Cordova related capabilities

- doc/Index.md
- doc/scenario/add_single_file_generator.md
> Single file generators

- doc/Index.md
- doc/extensibility/IProjectTreePropertiesProvider.md
- doc/overview/about_project_capabilities.md
- doc/overview/dynamicCapabilities.md
> Add document for dynamic capabilities

- doc/overview/breaking_changes_visual_studio_next.md
> Added ProjectAutoLoad breaking change

- doc/overview/reference_implementations.md
> Updated link to C#/VB

- doc/extensibility/IProjectGlobalPropertiesProvider.md
Correct the document title and add a better example.
> Update IProjectGlobalPropertiesProvider doc

- doc/overview/globbing_behavior.md
This PR adds a document that outlines the behavior CPS will use in a glob-enabled document. Feel free to discuss the behavior in this PR.
> Add globbing behavior document

- doc/overview/project_capabilities.md
See https://github.com/dotnet/testimpact/issues/1119 for details.
> Add UnitTestContainer capability

- doc/overview/project_capabilities.md
Add NoGeneralDependentFileIcon capability description
> Add NoGeneralDependentFileIcon capability

- doc/Index.md
- doc/extensibility/dataflow_example.md
- doc/extensibility/dataflow_sources.md
- doc/overview/dataflow_in_CPS.md
Add documents giving a general outline of how dataflow works in CPS.
> Add dataflow documents

- samples/WindowsScript/WindowsScript/WindowsScript.ProjectType/ScriptDebuggerLaunchProvider.cs
- fixing unhandled exception
- wrapping cscript.exe in a cmd.exe process with wait message at the end of execution (Press any key to continue)
> Improving launching script without debugger (Ctrl + F5):

- .gitignore
- samples/CpsExtension/CpsExtension.Nuget/Build/CpsExtensionNuget.props
- samples/CpsExtension/CpsExtension.Nuget/Build/CpsExtensionNuget.targets
- samples/CpsExtension/CpsExtension.Nuget/CpsExtension.Nuget.csproj
- samples/CpsExtension/CpsExtension.Vsix/BuildSystem/CpsExtension.DesignTime.targets
- samples/CpsExtension/CpsExtension.Vsix/BuildSystem/Rules/CustomDebugger.xaml
- samples/CpsExtension/CpsExtension.Vsix/CpsExtension.Vsix.csproj
- samples/CpsExtension/CpsExtension.Vsix/CustomDebugger.cs
- samples/CpsExtension/CpsExtension.Vsix/ProjectCapability.cs
- samples/CpsExtension/CpsExtension.Vsix/Properties/launchSettings.json
- samples/CpsExtension/CpsExtension.Vsix/Rules/ProjectProperties.cs
- samples/CpsExtension/CpsExtension.Vsix/source.extension.vsixmanifest
- samples/CpsExtension/CpsExtension.sln
- samples/CpsExtension/README.md
Adds an example solution for extending existing CPS project types.
> Cps extension sample

- README.md
Point readme.md to the Visual Studio Extensibility channel.
> Update gitter channel

- doc/extensibility/custom_item_types.md
- doc/extensibility/property_pages.md
- doc/overview/contentitem_types.md
> Fix broken links

- CHANGES.md
Document changes to the FullPath property that will be coming in a future Visual Studio 2019 release.
> Document change to the FullPath property

- doc/scenario/provide_custom_icons_for_the_project_or_item_type.md
- fix IProjectTreePropertiesProvider doc link
> fixes IProjectTreePropertiesProvider doc link

- doc/extensibility/adding_xaml_rules.md
- doc/extensibility/extending_rules.md
Update the documentation on rules to reflect new rule sources and new abilities for extending rules defined in differing sources.
> Update docs on Rules

- doc/overview/intro.md
> Fix typo in intro.md
