- doc/extensibility/IProjectTreeModifier.md
Also changed scope from ConfiguredProject -> UnconfiguredProject.
> Expand information on IProjectTreeModifier

- doc/overview/scopes.md
Attempted to clarify the difference between the IVsSolution scope and the VS default container. The terms were used interchangeably which was confusing.
> Clarified scopes and the "global" scope

- doc/overview/project_capabilities.md
Those capability strings are used by some shipped products.
> Add project capabilities used by Azure projects and LightSwitch

- doc/overview/contentitem_types.md
Added missing info about how to make the new item type appear in the add -> new item dialog.
> Adding the item type to the add new item dialog

- doc/Index.md
- doc/extensibility/adding_xaml_rules.md
Documents the 3 ways to add xaml rules to CPS.
> Add documentation for adding rules to CPS

- doc/extensibility/IDebugLaunchProvider.md
Adds an example showing how the `DebugLaunchProviderBase` works.
> Add IDebugLaunchProvider example

- doc/extensibility/IProjectGlobalPropertiesProvider.md
It doesn't receive the old parameter.
> Fix updated base type constructor

- doc/extensibility/project_item_templates.md
It was not clear to me in reading these docs that this SDK was a separate download. I had installed the "Visual Studio extension development" toolset in the VS installer, but none of the items in these docs were showing up. It was very confusing. Hoping this link will help clarify.
> Add link to SDK download

- doc/overview/project_capabilities.md
Fixes: #328 
I think the proper naming should be `TestContainer` as it is used in `Microsoft.NET.Test.Sdk`.
https://github.com/microsoft/vstest/blob/f0cd370fa400b9e6ab220096b5a8f14a028ac4f2/src/package/nuspec/Microsoft.NET.Test.Sdk.props#L19-L21
> Rename UnitTestContainer to TestContainer

- doc/extensibility/IDynamicEnumValuesProvider.md
Headings need a white space between the `#` characters and the heading text to render property on GitHub.
> Fix heading formatting in IDynamicEnumValuesProvider.md

- doc/automation/notification_for_async_project_load_completion.md
The SatisfyImportsOnce extension method does not exist on `UnconfiguredProject`.
> Fix code sample for obtaining tree service

- doc/extensibility/property_pages.md
A previous commit attempted to fix up these links to point to updated
locations on docs.microsoft.com instead of blogs.msdn.com. However, the
updated links actually pointed to unrelated documentation--with a
similar name--on creating a new project system based on MPF (the Managed
Project Framework), rather than the blog posts on creating property
pages in a CPS-based project system. This commit corrects the links.
> Fix links to blog posts

- doc/overview/about_project_capabilities.md
VB projects do actually use the `VB` capability. While that may not have been the best choice given this guidance, we can at least update the documentation to use an example that doesn't exist in common use.
(Pointed out by Jason Malinowski via email.)
> Update example of a bad capability

- doc/scenario/provide_custom_icons_for_the_project_or_item_type.md
- Headings need a space after the `##` characters.
- Nested content within lists needs three spaces to display correctly.
> Fix markdown formatting

- samples/WindowsScript/WindowsScript/WindowsScript.ProjectTemplate/WindowsScript.wsproj
- samples/WindowsScript/WindowsScript/WindowsScript.ProjectType/WindowsScript.ProjectType.csproj
- samples/WindowsScript/WindowsScript/WindowsScript.ProjectType/source.extension.vsixmanifest
VSIX v3 can install files to a few locations outside the VS extensions folder, including the MSBuild extensions folder, so an MSI installer for the project system extension is not required. 
I changed the sample project to demonstrate how to get the files included in the VSIX, and I changed the sample template to import the props and targets files from the MSBuild extensions folder.
> Install MSBuild and rules files with VSIX

- doc/overview/project_capabilities.md
Mentioning F# is missing from the table.
https://github.com/dotnet/project-system/blob/main/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectCapability.cs#L12
> Extend project capabilities with F# language

- doc/Index.md
- doc/overview/dataflow.md
From https://github.com/dotnet/project-system/issues/9099:
> Dataflow is one of the most daunting areas for contributors to the project system. We have various bits of documentation spread across several repositories but most of it is fairly advanced or provided without enough context to know whether it's relevant to what you're trying to do. We should have a single document that walks the reader through all the relevant concepts, building things up in a thought-out fashion, that is both readable top-to-bottom and as a reference for specific topics.
This document aims to provide that.
I'm putting this draft PR up to gather feedback.
> Add new Dataflow documentation

- doc/extensibility/adding_xaml_rules.md
Packages are no longer on nuget.org, so fix the link to avoid confusion.
> Fix URL for package source

- doc/extensibility/extending_rules.md
- samples/CpsExtension/CpsExtension.Nuget/Build/CpsExtension.Nuget.targets
- samples/CpsExtension/CpsExtension.Nuget/CpsExtension.Nuget.csproj
- samples/CpsExtension/CpsExtension.Vsix/BuildSystem/CpsExtension.DesignTime.targets
- samples/CpsExtension/CpsExtension.Vsix/BuildSystem/Rules/Compile.BrowseObject.xaml
- samples/CpsExtension/CpsExtension.Vsix/CpsExtension.Vsix.csproj
- samples/CpsExtension/CpsExtension.Vsix/CustomDebugger.cs
- samples/CpsExtension/CpsExtension.Vsix/Properties/launchSettings.json
- samples/CpsExtension/CpsExtension.Vsix/source.extension.vsixmanifest
- samples/CpsExtension/README.md
- Update the project to Dev 17
- Adding rule showing how to add a custom property to a Compile item in SDK-style project
- Fixing an issue that was causing a Non Fatal Exception (NFE displayed as yellow bar) due to MEF failing to instantiate the CustomDebugger class due to using the `ImportingConstructor` attribute from the wrong namespace
- Adding a workaround to copy the rule files to the output folder (being skipped by MSBuild)
- Fixing an issue that was causing extra assemblies to be embedded within the vsix
- Updating documentation
> Updating CpsExtension sample to Dev 17, extending existing rule, fixes

- doc/automation/obtaining_the_MSBuild.Project_from_CPS.md
- doc/overview/mef.md
- doc/overview/threading_model.md
- doc/overview/threading_rules.md
In a chat with a partner team today I was looking for a doc to explain how to pull a MEF component from a project, when not a suitably-scoped MEF component yourself.
This information is touched on in `finding_CPS_in_a_VS_project.md`, but feels more discoverable in `mef.md`.
> Document obtaining MEF components from projects
